// automatic generated by vnlex
static _vn_ns::LR_Terminal g_keywordInfo[] = {
	{"false", 1},
	{"true", 2},
	{(const char *)0, 0}
};

static _vn_ns::LR_Terminal g_symbolInfo[] = {
	{"+", 1},
	{"-", 2},
	{"=", 3},
	{"@", 4},
	{"@<", 5},
	{"@>", 6},
	{"[", 7},
	{"]", 8},
	{"{", 9},
	{"}", 10},
	{(const char *)0, 0}
};

static _vn_ns::LR_Jump g_state0_jumps[] = {
	_vn_ns::LR_Jump(9, 1),
	_vn_ns::LR_Jump(6, 2),
	_vn_ns::LR_Jump(5, 3),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state1_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state1_reduction = {
	1, 0, 0
};

static _vn_ns::LR_Jump g_state2_jumps[] = {
	_vn_ns::LR_Jump(5, 5),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state2_reduction = {
	1, 30, 9
};

static _vn_ns::LR_Jump g_state3_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state3_reduction = {
	1, 26, 6
};

static _vn_ns::LR_Jump g_state4_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 6),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state5_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state5_reduction = {
	2, 27, 6
};

static _vn_ns::LR_Jump g_state6_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 7),
	_vn_ns::LR_Jump(4, 8),
	_vn_ns::LR_Jump(6, 9),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 9, 10),
	_vn_ns::LR_Jump(5, 3),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state7_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 11),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state8_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 12),
	_vn_ns::LR_Jump(6, 13),
	_vn_ns::LR_Jump(5, 3),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state9_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 14),
	_vn_ns::LR_Jump(5, 5),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state10_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 10, 15),
	_vn_ns::LR_Jump(3, 16),
	_vn_ns::LR_Jump(2, 17),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 18),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state11_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state11_reduction = {
	4, 22, 5
};

static _vn_ns::LR_Jump g_state12_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 19),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state13_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 6, 20),
	_vn_ns::LR_Jump(5, 5),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state14_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 21),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state15_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state15_reduction = {
	2, 19, 4
};

static _vn_ns::LR_Jump g_state16_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 10, 22),
	_vn_ns::LR_Jump(2, 23),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 18),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state17_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state17_reduction = {
	1, 17, 3
};

static _vn_ns::LR_Jump g_state18_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 3, 24),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state19_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state19_reduction = {
	5, 23, 5
};

static _vn_ns::LR_Jump g_state20_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 25),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state21_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state21_reduction = {
	5, 24, 5
};

static _vn_ns::LR_Jump g_state22_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state22_reduction = {
	3, 20, 4
};

static _vn_ns::LR_Jump g_state23_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state23_reduction = {
	2, 18, 3
};

static _vn_ns::LR_Jump g_state24_jumps[] = {
	_vn_ns::LR_Jump(10, 26),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 27),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 28),
	_vn_ns::LR_Jump(7, 29),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 1, 30),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 2, 31),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 32),
	_vn_ns::LR_Jump(1, 33),
	_vn_ns::LR_Jump(8, 34),
	_vn_ns::LR_Jump(5, 35),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 36),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 37),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 38),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 39),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 7, 40),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 4, 41),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state25_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state25_reduction = {
	6, 25, 5
};

static _vn_ns::LR_Jump g_state26_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state26_reduction = {
	3, 16, 2
};

static _vn_ns::LR_Jump g_state27_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state27_reduction = {
	1, 1, 10
};

static _vn_ns::LR_Jump g_state28_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state28_reduction = {
	1, 2, 10
};

static _vn_ns::LR_Jump g_state29_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state29_reduction = {
	1, 3, 10
};

static _vn_ns::LR_Jump g_state30_jumps[] = {
	_vn_ns::LR_Jump(7, 42),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 36),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 37),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 38),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 39),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state31_jumps[] = {
	_vn_ns::LR_Jump(7, 43),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 36),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 37),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 38),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 39),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state32_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state32_reduction = {
	1, 6, 10
};

static _vn_ns::LR_Jump g_state33_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state33_reduction = {
	1, 7, 10
};

static _vn_ns::LR_Jump g_state34_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state34_reduction = {
	1, 8, 10
};

static _vn_ns::LR_Jump g_state35_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state35_reduction = {
	1, 9, 10
};

static _vn_ns::LR_Jump g_state36_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state36_reduction = {
	1, 10, 7
};

static _vn_ns::LR_Jump g_state37_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state37_reduction = {
	1, 11, 7
};

static _vn_ns::LR_Jump g_state38_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state38_reduction = {
	1, 12, 7
};

static _vn_ns::LR_Jump g_state39_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state39_reduction = {
	1, 13, 7
};

static _vn_ns::LR_Jump g_state40_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 8, 44),
	_vn_ns::LR_Jump(11, 45),
	_vn_ns::LR_Jump(10, 46),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 27),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 28),
	_vn_ns::LR_Jump(7, 29),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 1, 30),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 2, 31),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 32),
	_vn_ns::LR_Jump(1, 33),
	_vn_ns::LR_Jump(8, 34),
	_vn_ns::LR_Jump(5, 35),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 36),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 37),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 38),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 39),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 7, 40),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 4, 41),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state41_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 1, 0, 47),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state42_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state42_reduction = {
	2, 4, 10
};

static _vn_ns::LR_Jump g_state43_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state43_reduction = {
	2, 5, 10
};

static _vn_ns::LR_Jump g_state44_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state44_reduction = {
	2, 28, 1
};

static _vn_ns::LR_Jump g_state45_jumps[] = {
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 8, 48),
	_vn_ns::LR_Jump(10, 49),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 2, 27),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 10, 1, 28),
	_vn_ns::LR_Jump(7, 29),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 1, 30),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 2, 31),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 9, 0, 32),
	_vn_ns::LR_Jump(1, 33),
	_vn_ns::LR_Jump(8, 34),
	_vn_ns::LR_Jump(5, 35),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 5, 0, 36),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 6, 0, 37),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 7, 0, 38),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kToken, 8, 0, 39),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 7, 40),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 4, 41),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 5, 4),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state46_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state46_reduction = {
	1, 14, 11
};

static _vn_ns::LR_Jump g_state47_jumps[] = {
	_vn_ns::LR_Jump(4, 50),
	_vn_ns::LR_Jump(_vn_ns::LR_Jump::kTokenWithValue, 2, 9, 10),
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Jump g_state48_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state48_reduction = {
	3, 29, 1
};

static _vn_ns::LR_Jump g_state49_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state49_reduction = {
	2, 15, 11
};

static _vn_ns::LR_Jump g_state50_jumps[] = {
	_vn_ns::LR_Jump()
};

static _vn_ns::LR_Reduction g_state50_reduction = {
	3, 21, 8
};

static _vn_ns::LR_State g_states[] = {
	{0, g_state0_jumps, (_vn_ns::LR_Reduction *)0},
	{1, g_state1_jumps, &g_state1_reduction},
	{2, g_state2_jumps, &g_state2_reduction},
	{3, g_state3_jumps, &g_state3_reduction},
	{4, g_state4_jumps, (_vn_ns::LR_Reduction *)0},
	{5, g_state5_jumps, &g_state5_reduction},
	{6, g_state6_jumps, (_vn_ns::LR_Reduction *)0},
	{7, g_state7_jumps, (_vn_ns::LR_Reduction *)0},
	{8, g_state8_jumps, (_vn_ns::LR_Reduction *)0},
	{9, g_state9_jumps, (_vn_ns::LR_Reduction *)0},
	{10, g_state10_jumps, (_vn_ns::LR_Reduction *)0},
	{11, g_state11_jumps, &g_state11_reduction},
	{12, g_state12_jumps, (_vn_ns::LR_Reduction *)0},
	{13, g_state13_jumps, (_vn_ns::LR_Reduction *)0},
	{14, g_state14_jumps, (_vn_ns::LR_Reduction *)0},
	{15, g_state15_jumps, &g_state15_reduction},
	{16, g_state16_jumps, (_vn_ns::LR_Reduction *)0},
	{17, g_state17_jumps, &g_state17_reduction},
	{18, g_state18_jumps, (_vn_ns::LR_Reduction *)0},
	{19, g_state19_jumps, &g_state19_reduction},
	{20, g_state20_jumps, (_vn_ns::LR_Reduction *)0},
	{21, g_state21_jumps, &g_state21_reduction},
	{22, g_state22_jumps, &g_state22_reduction},
	{23, g_state23_jumps, &g_state23_reduction},
	{24, g_state24_jumps, (_vn_ns::LR_Reduction *)0},
	{25, g_state25_jumps, &g_state25_reduction},
	{26, g_state26_jumps, &g_state26_reduction},
	{27, g_state27_jumps, &g_state27_reduction},
	{28, g_state28_jumps, &g_state28_reduction},
	{29, g_state29_jumps, &g_state29_reduction},
	{30, g_state30_jumps, (_vn_ns::LR_Reduction *)0},
	{31, g_state31_jumps, (_vn_ns::LR_Reduction *)0},
	{32, g_state32_jumps, &g_state32_reduction},
	{33, g_state33_jumps, &g_state33_reduction},
	{34, g_state34_jumps, &g_state34_reduction},
	{35, g_state35_jumps, &g_state35_reduction},
	{36, g_state36_jumps, &g_state36_reduction},
	{37, g_state37_jumps, &g_state37_reduction},
	{38, g_state38_jumps, &g_state38_reduction},
	{39, g_state39_jumps, &g_state39_reduction},
	{40, g_state40_jumps, (_vn_ns::LR_Reduction *)0},
	{41, g_state41_jumps, (_vn_ns::LR_Reduction *)0},
	{42, g_state42_jumps, &g_state42_reduction},
	{43, g_state43_jumps, &g_state43_reduction},
	{44, g_state44_jumps, &g_state44_reduction},
	{45, g_state45_jumps, (_vn_ns::LR_Reduction *)0},
	{46, g_state46_jumps, &g_state46_reduction},
	{47, g_state47_jumps, (_vn_ns::LR_Reduction *)0},
	{48, g_state48_jumps, &g_state48_reduction},
	{49, g_state49_jumps, &g_state49_reduction},
	{50, g_state50_jumps, &g_state50_reduction},
	{0xFFFFFFFF, (_vn_ns::LR_Jump *)0, (_vn_ns::LR_Reduction *)0}
};
